name: Create release tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release version"
        required: true
        default: "v1.0.0"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git config --local user.email "<>"
          git config --local user.name "GitHub Actions"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"
      - name: Dispatch build_cli workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          event-type: create-release
          client-payload: '{"tag": "${{ github.event.inputs.tag }}"}'
